import Head from 'next/head'
import Navbar from '../../../components/Navbar'
import SmoothScroll from '../../../components/Helpers/SmoothScroll'
import Footer from '../../../components/Footer'
import Hero from '../../../components/Blog/Hero'
import Grid from '../../../components/Blog/Grid'

export default function Blog({ setOpen }) {
  SmoothScroll()

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-white relative'>
        <Navbar setOpen={setOpen} header />
        <Hero />
        <Grid />
        <Footer />
      </div>
    </>
  )
}
