import Head from 'next/head'
// import { Archivo, Rubik, Unbounded, } from 'next/font/google'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Home/Hero'
import Servicios from '../../components/Home/ServiciosSection'
import ColoredTitle from '../../components/Home/ColoredTitle'
import SmoothScroll from '../../components/Helpers/SmoothScroll'
import ContactSection from '../../components/ContactSection'
import Footer from '../../components/Footer'
import HomeTools from '../../components/Home/HomeTools'

// const archivo = Archivo({ subsets: ['latin'] })


export default function Home({setOpen}) {

  SmoothScroll()
  return (
    <>
      <Head>
        <title>Zinco</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-white'>
        <Navbar setOpen={setOpen}/>
        <Hero />
        <Servicios />
        <ColoredTitle />
        <HomeTools />
        <ContactSection />
        <Footer />
      </div>
    </>
  )
}
