import Head from 'next/head'
import Navbar from '../../components/Navbar'
import SmoothScroll from '../../components/Helpers/SmoothScroll'
import Hero from '../../components/Services/Hero'
import AccordionsDiv from '../../components/Services/AccordionsDiv'
import Projects from '../../components/Services/Projects'
import ContactSection from '../../components/ContactSection'
import Footer from '../../components/Footer'
import Process from '../../components/Services/Process'

export default function About({ setOpen }) {
  SmoothScroll()

  return (
    <>
      <Head>
        <title>Servicios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-white relative'>
        <Navbar setOpen={setOpen} header />
        <Hero />
        <div className='w-full bg-[#3e3391] h-[1px] my-14 md:mt-28 md:mb-24'></div>
        <AccordionsDiv />
        <Projects />
        <div className='w-full bg-[#3e3391] h-[1px] my-14 md:mt-28 md:mb-24'></div>
        <Process />
        <ContactSection smallTitle />
        <Footer />
      </div>
    </>
  )
}
